package telefood.gui;

import telefood.logica.FTPUploader;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.UUID;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import telefood.logica.Registro;
import telefood.logica.TeleFood;

public class frmEditarProducto extends javax.swing.JFrame {
    
    ArrayList<Object> datos = new ArrayList();
    int productoId;
    String uniqueImage = null;

    TeleFood producto = null;
    frmProductos ventana = null;

    public frmEditarProducto(TeleFood producto, Registro registro) {
        this.producto=producto;
        this.datos = registro.getDatos();
        initComponents();
        
        productoId = Integer.valueOf(datos.get(0).toString());
        if (datos.get(1) != null) {
            if (!datos.get(1).toString().equals("")) {
                uniqueImage = datos.get(1).toString();
            }
            txtImagePath.setText(uniqueImage);
        }
        txtProducto.setText(datos.get(2).toString());
        txtCosto.setText(datos.get(3).toString());
        
        if (Integer.valueOf(datos.get(4).toString())==0){
            jRadioNo.setSelected(true);
            jRadioSi.setSelected(false);
        } else {
            jRadioSi.setSelected(true);
            jRadioNo.setSelected(false);
        }
        
        if (Integer.valueOf(datos.get(5).toString())==0){
            cmbCategoria.setSelectedIndex(0);
        } else {
            cmbCategoria.setSelectedIndex(1);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new ThumbnailFileChooser();
        btnGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        cmbCategoria = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtImagePath = new javax.swing.JTextField();
        btnPickImage = new javax.swing.JButton();
        jRadioNo = new javax.swing.JRadioButton();
        jRadioSi = new javax.swing.JRadioButton();

        jFileChooser1.setCurrentDirectory(new File
            (System.getProperty("user.home") + System.getProperty("file.separator")+ "Pictures"));
        jFileChooser1.setDialogTitle("Seleccione una imagen para el producto.");
        jFileChooser1.setFileFilter(new FileNameExtensionFilter(
            "Imágenes", ImageIO.getReaderFileSuffixes()));
    jFileChooser1.setAcceptAllFileFilterUsed(false);

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telefood/gui/img/guardar.png"))); // NOI18N
    btnGuardar.setText("Guardar");
    btnGuardar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnGuardarActionPerformed(evt);
        }
    });

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telefood/gui/img/logo 2.png"))); // NOI18N

    jLabel2.setFont(new java.awt.Font("Script MT Bold", 2, 28)); // NOI18N
    jLabel2.setText("TeleFood");

    jLabel3.setText("Categoria:");

    jLabel4.setText("Producto:");

    jLabel5.setText("Costo:");

    jLabel6.setText("Oferta:");

    jLabel7.setText("Ingreso de producto:");

    btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telefood/gui/img/cancelar.png"))); // NOI18N
    btnCancelar.setText("Cancelar");
    btnCancelar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCancelarActionPerformed(evt);
        }
    });

    cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bebida", "Comida" }));

    jLabel8.setText("Imagen:");

    txtImagePath.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            txtImagePathMouseClicked(evt);
        }
    });
    txtImagePath.setEditable(false);

    btnPickImage.setText("Seleccionar");
    btnPickImage.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnPickImageActionPerformed(evt);
        }
    });

    jRadioNo.setSelected(true);
    jRadioNo.setText("No");
    jRadioNo.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jRadioNoActionPerformed(evt);
        }
    });

    jRadioSi.setText("Sí");
    jRadioSi.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jRadioSiActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnPickImage, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                                    .addComponent(txtCosto)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioSi)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioNo))))))
                    .addGap(15, 15, 15))))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel7))
                .addGroup(layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(jLabel2)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(btnPickImage, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel4))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6)
                .addComponent(jRadioNo)
                .addComponent(jRadioSi))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnGuardar)
                .addComponent(btnCancelar))
            .addContainerGap())
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        
        boolean imagen = false;
        
        if(uniqueImage==null){
            if (!txtImagePath.getText().equals("")) {
                File file = new File(txtImagePath.getText());
                try {
                    FTPUploader ftpUploader = new FTPUploader("ftp.wwecuador.com", "wwecuado_ft@wwecuador.com", "T3l3f00d!\"");
                    String extension = file.getName().substring(file.getName().indexOf("."));
                    uniqueImage = UUID.randomUUID().toString() + extension;
                    ftpUploader.uploadFile(file.getPath(), uniqueImage, "");
                    ftpUploader.disconnect();
                    imagen = true;
                } catch (Exception ex) {
                    System.err.println("Error subiendo imagen: " + ex.getMessage());
                }
            }
        } else {
            if (txtImagePath.getText().contains("\\")) {
                File file = new File(txtImagePath.getText());
                try {
                    FTPUploader ftpUploader = new FTPUploader("ftp.wwecuador.com", "wwecuado_ft@wwecuador.com", "T3l3f00d!\"");
                    ftpUploader.uploadFile(file.getPath(), uniqueImage, "");
                    ftpUploader.disconnect();
                } catch (Exception ex) {
                    System.err.println("Error subiendo imagen: " + ex.getMessage());
                }
            }
        }

        Registro reg = new Registro();
        String campos[];
        campos = new String[] {"ProductoId", "Imagen", "Nombre", "Precio", 
            "EstaEnOferta", "Tipo"};
        int tipo = 0;
        reg.setDatos(productoId);
        reg.setDatos(uniqueImage);
        reg.setDatos(txtProducto.getText());
        reg.setDatos(txtCosto.getText());
        
        if (jRadioNo.isSelected()){
            reg.setDatos(0);
        } else {
            reg.setDatos(1);
        }
        
        if (cmbCategoria.getSelectedItem().equals("Comida")) {
            tipo = 1;
        }
        reg.setDatos(tipo);
        
        ArrayList<String> camposEditados = new ArrayList<>();
        if (reg.getDatos().get(1)==null){
            camposEditados.add("Imagen=NULL");
        } else {
            camposEditados.add("Imagen='"+reg.getDatos().get(1).toString()+"'");
        }
        camposEditados.add("Nombre='"+reg.getDatos().get(2).toString()+"'");
        camposEditados.add("Precio="+reg.getDatos().get(3).toString());
        camposEditados.add("EstaEnOferta="+reg.getDatos().get(4).toString());
        camposEditados.add("Tipo="+reg.getDatos().get(5).toString());
        
        ArrayList<String> claves = new ArrayList<>();
        claves.add("ProductoId="+reg.getDatos().get(0).toString());

        try {
            producto.editarDatos("Producto", claves, camposEditados);
            dispose();
        } catch (Exception ex) {
            System.err.println("Error: " + ex.getMessage());
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnPickImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPickImageActionPerformed
        // TODO add your handling code here:
        //Handle open button action.
        int returnVal = jFileChooser1.showOpenDialog(frmEditarProducto.this);

        if (returnVal == jFileChooser1.APPROVE_OPTION) {
            File file = jFileChooser1.getSelectedFile();
            try {
                BufferedImage bimg = ImageIO.read(file);
                if (bimg.getHeight()<=566 && bimg.getWidth()<=850){
                    txtImagePath.setText(file.getAbsolutePath());
                } else {
                    JOptionPane.showMessageDialog(this, "El tamaño máximo es de"
                    + " 850 x 566 px.", "Archivo incorrecto.", JOptionPane.ERROR_MESSAGE);
                    txtImagePath.setText("");
                }
                //This is where a real application would open the file.
            } catch (IOException ex) {
                txtImagePath.setText("");
                System.err.println("Error: " + ex.getMessage());
            }
        } else {
            txtImagePath.setText("");
        }
    }//GEN-LAST:event_btnPickImageActionPerformed

    private void txtImagePathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtImagePathMouseClicked
        // TODO add your handling code here:
        int returnVal = jFileChooser1.showOpenDialog(frmEditarProducto.this);

        if (returnVal == jFileChooser1.APPROVE_OPTION) {
            File file = jFileChooser1.getSelectedFile();
            try {
                BufferedImage bimg = ImageIO.read(file);
                if (bimg.getHeight()<=566 && bimg.getWidth()<=850){
                    txtImagePath.setText(file.getAbsolutePath());
                } else {
                    JOptionPane.showMessageDialog(this, "El tamaño máximo es de"
                    + " 850 x 566 px.", "Archivo incorrecto.", JOptionPane.ERROR_MESSAGE);
                    txtImagePath.setText("");
                }
                //This is where a real application would open the file.
            } catch (IOException ex) {
                txtImagePath.setText("");
                System.err.println("Error: " + ex.getMessage());
            }
        } else {
            txtImagePath.setText("");
        }
    }//GEN-LAST:event_txtImagePathMouseClicked

    private void jRadioSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioSiActionPerformed
        // TODO add your handling code here:
        jRadioNo.setSelected(false);
        jRadioSi.setSelected(true);
    }//GEN-LAST:event_jRadioSiActionPerformed

    private void jRadioNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioNoActionPerformed
        // TODO add your handling code here:
        jRadioNo.setSelected(true);
        jRadioSi.setSelected(false);
    }//GEN-LAST:event_jRadioNoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnPickImage;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioNo;
    private javax.swing.JRadioButton jRadioSi;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtImagePath;
    private javax.swing.JTextField txtProducto;
    // End of variables declaration//GEN-END:variables
}
