/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telefood.gui;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.table.DefaultTableModel;
import telefood.logica.Producto;
import telefood.logica.Registro;
import telefood.logica.TeleFood;

/**
 *
 * @author Jorge
 */
public class frmHacerPedido extends javax.swing.JFrame {

    TeleFood pedidos = null;
    ArrayList<Producto> listaProductos = new ArrayList<>();
    ArrayList<Integer> listaIds = new ArrayList<>();

    /**
     * Creates new form frmControlPedidos
     */
    public frmHacerPedido(TeleFood pedidos) throws Exception {
        initComponents();
        this.pedidos = pedidos;
        llenar();
        Action action = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                TableCellListener tcl = (TableCellListener) e.getSource();
                try {
                    if (Boolean.valueOf(tcl.getNewValue().toString()) == true) {
                        tbPedidos.setValueAt(1, tcl.getRow(), 1);
                    } else {
                        if (!(tcl.getColumn()==1)){
                            tbPedidos.setValueAt(0, tcl.getRow(), 1);
                        }
                    }
                } catch (Exception ex) {
                    System.err.println("Error: " + ex.getMessage());
                }
                
            }
        };
        TableCellListener tcl = new TableCellListener(tbPedidos, action);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSiguiente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPedidos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telefood/gui/img/siguiente.png"))); // NOI18N
        btnSiguiente.setText("Hacer Pedido");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        tbPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Seleccionar", "Cantidad", "Nombre", "Oferta", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbPedidos);
        if (tbPedidos.getColumnModel().getColumnCount() > 0) {
            tbPedidos.getColumnModel().getColumn(0).setResizable(false);
            tbPedidos.getColumnModel().getColumn(1).setResizable(false);
            tbPedidos.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel3.setFont(new java.awt.Font("Script MT Bold", 0, 22)); // NOI18N
        jLabel3.setText("Pedidos");

        jLabel2.setFont(new java.awt.Font("Script MT Bold", 2, 28)); // NOI18N
        jLabel2.setText("TeleFood  ");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telefood/gui/img/logo 2.png"))); // NOI18N

        jLabel4.setText("Número de Tarjeta:");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telefood/gui/img/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(136, 136, 136)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(107, 107, 107)
                                        .addComponent(jLabel2)))
                                .addGap(93, 93, 93))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSiguiente)
                .addGap(182, 182, 182))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(11, 11, 11)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiguiente)
                    .addComponent(btnCancelar))
                .addGap(34, 34, 34))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void llenar() throws Exception {
        //SELECT  From Pedido ;
        //Array String, String, String

        ArrayList<String> campo = new ArrayList();
        campo.add("Nombre");
        campo.add("EstaEnOferta");
        campo.add("Precio");
        campo.add("ProductoId");
        Registro r = new Registro();
        r.setDatos(campo);
        r.setDatos("Producto");
        r.setDatos("Tipo=0");
        ArrayList<Registro> registro = pedidos.listarDatos(r);
        
        DefaultTableModel tm = (DefaultTableModel) tbPedidos.getModel();
        tm.setRowCount(0);
        int i = 0;
        for (Registro reg : registro) {
            int j = 2;
            tm.addRow(new Object[]{""});
            tm.setValueAt(false, i, 0);
            tm.setValueAt(0, i, 1);
            for (Object dat : reg.getDatos()) {
                switch (j) {
                    case 2:
                        tm.setValueAt(dat.toString(), i, j);
                        break;
                    case 3:
                        tm.setValueAt(Boolean.valueOf(dat.toString()), i, j);
                        break;
                    case 4:
                        tm.setValueAt(Double.parseDouble(dat.toString()), i, j);
                        break;
                    case 5:
                        listaIds.add(Integer.valueOf(dat.toString()));
                        break;
                    default:
                        break;
                }
                j++;
            }
            i++;
        }

    }


    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed

        DefaultTableModel tm = (DefaultTableModel) tbPedidos.getModel();
        for (int i = 0; i < tm.getRowCount(); i++) {
            if (Boolean.valueOf(tbPedidos.getValueAt(i, 0).toString()) == true) {
                Producto prod = new Producto();
                prod.setCantidad(tbPedidos.getValueAt(i, 1).toString());
                prod.setNombre(tbPedidos.getValueAt(i, 2).toString());
                prod.setPrecio(Double.parseDouble(tbPedidos.getValueAt(i, 4).toString()));
                prod.setProductoId(listaIds.get(i));
                listaProductos.add(prod);
            }
        }
        
        int numeroTarjeta = Integer.parseInt(jSpinner1.getValue().toString());
        
        //Insertar Pedido
        //INSERT INTO Pedido VALUES(default, T+numeroTarjeta, curdate(), curtime(), 0)
        Registro reg = new Registro();
        reg.setDatos("DEFAULT");
        reg.setDatos("T"+numeroTarjeta);
        reg.setDatos("curdate()");
        reg.setDatos("curtime()");
        reg.setDatos(1);
        
        try {
            pedidos.insertarDatos("Pedido", reg);
        } catch (Exception ex) {
            System.err.println("Error: " + ex.getMessage());
        }
        
        
        for (int i = 0; i < listaProductos.size(); i++) {
            Producto prodActual = listaProductos.get(i);
            String prodId = String.valueOf(prodActual.getProductoId());
            String prodCantidad = prodActual.getCantidad();
            String prodPrecio = String.valueOf(prodActual.getPrecio());
            
            reg = new Registro();
            reg.setDatos("(SELECT MAX(PedidoId) FROM Pedido)");
            reg.setDatos(prodId);
            reg.setDatos(null);
            reg.setDatos(prodCantidad);
            reg.setDatos(prodPrecio);

            //INSERT INTO Pedido_Producto VALUES((SELECT MAX(PedidoId) FROM Pedido),
            // prodId, null, prodCantidad, prodPrecio)
            try {
                pedidos.insertarDatos("Pedido_Producto", reg);
            } catch (Exception ex) {
                System.err.println("Error: " + ex.getMessage());
            }
        }
        
        dispose();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnAtras1;
    private javax.swing.JButton btnAtras2;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable tbPedidos;
    // End of variables declaration//GEN-END:variables
}
