/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telefood.gui;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import telefood.logica.Registro;
import telefood.logica.TeleFood;

/**
 *
 * @author dell
 */
public class frmProductos extends javax.swing.JFrame {
    
    int columna, fila, id;
    Registro registroPaso = new Registro();
    boolean isChanging = false;
    boolean primeraVez = true;

    static TeleFood productos = null;

    public frmProductos(TeleFood productos) throws Exception {
        initComponents();
        this.productos = productos;
        llenar();
        tbListaProductos.getSelectionModel().addListSelectionListener(
                (ListSelectionEvent e) -> {
                    if (!tbListaProductos.getSelectionModel().isSelectionEmpty()) {
                        btnEditar.setEnabled(true);
                        registroPaso.getDatos().clear();
                        
                        for (int i=0; i<tbListaProductos.getColumnCount(); i++) {
                            registroPaso.setDatos(tbListaProductos.getValueAt(
                                    tbListaProductos.getSelectedRow(), i));
                        }
                        
                    } else {
                        btnEditar.setEnabled(false);
                    }
                }
        );
    }

    public void llenar() throws Exception {
        ArrayList<String> columnas = productos.camposTabla("Producto");
        System.out.println(columnas);

        DefaultTableModel tb = (DefaultTableModel) tbListaProductos.getModel();
        tb.setColumnCount(0);
        tb.setRowCount(0);
        for (String campo : columnas) {
            tb.addColumn(campo);
        }

        ArrayList<Registro> registros = productos.listarRegistros("Producto");

        int i = 0;
        for (Registro reg : registros) {
            int j = 0;
            
            tb.addRow(new Object[]{""});
            for (Object dat : reg.getDatos()) {
                tb.setValueAt(dat, i, j);
                j++;
            }
            
            i++;
        }
        labelCargando.setVisible(false);
        labelImageCargando.setVisible(false);
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListaProductos = new javax.swing.JTable(){private static final long serialVersionUID = 1L;

            public boolean isCellEditable(int row, int column) {
                return false;
            };
        };
        btnAceptar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        labelCargando = new javax.swing.JLabel();
        URL url = getClass().getResource("/telefood/gui/img/loading_circle.gif");
        ImageIcon imageIcon = new ImageIcon(url);
        labelImageCargando = new javax.swing.JLabel(imageIcon);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telefood/gui/img/logo 2.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Script MT Bold", 0, 22)); // NOI18N
        jLabel3.setText("Lista De Productos");

        jLabel2.setFont(new java.awt.Font("Script MT Bold", 2, 28)); // NOI18N
        jLabel2.setText("TeleFood");

        jLabel4.setText("Agregar/Eliminar Producto");

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telefood/gui/img/agregar.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telefood/gui/img/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tbListaProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbListaProductos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbListaProductos);

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telefood/gui/img/aceptar.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telefood/gui/img/edit.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        labelCargando.setText("Cargando...");
        labelCargando.setOpaque(true);

        labelImageCargando.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telefood/gui/img/loading_circle.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(btnAceptar)
                        .addGap(70, 70, 70)
                        .addComponent(labelCargando)
                        .addGap(18, 18, 18)
                        .addComponent(labelImageCargando))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAgregar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEditar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEliminar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnEliminar)
                    .addComponent(btnAgregar)
                    .addComponent(btnEditar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelImageCargando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAceptar)
                        .addComponent(labelCargando)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        frmNuevoProducto ventana = new frmNuevoProducto(productos);
        tbListaProductos.clearSelection();
        ventana.addWindowListener(new WindowAdapter()
        {
            @Override
            public void windowClosed(WindowEvent e) {
                labelImageCargando.setVisible(true);
                    //To change body of generated methods, choose Tools | Templates.
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            try {
                                llenar();
                            } catch (Exception ex) {
                                System.err.println("Error: " + ex.getMessage());
                            }
                        }
                    });
            }
            
        });

        ventana.setVisible(true);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        DefaultTableModel tb = (DefaultTableModel) tbListaProductos.getModel();
        ArrayList<String> camposClave = new ArrayList();
        int i = tbListaProductos.getSelectedRow();
        Registro reg = new Registro();
        System.out.println("Posicion Eliminar:" + i);
        try {
            for (int j = 0; j < tb.getColumnCount(); j++) {
                if (tb.getColumnName(j).contains("Id")) {
                    camposClave.add(tb.getColumnName(j) + "='" + (String) tb.getValueAt(i, j) + "'");
                }
                reg.setDatos(tb.getValueAt(i, j));
            }

            int res = JOptionPane.showConfirmDialog(rootPane, "Esta seguro que desea eliminar:\n" + reg.getDatos(), "ELIMINAR (CONFIRMACION)", 0);
            if (res == 0) {
                productos.eliminarDatos("Producto", camposClave);
                llenar();
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Seleccione la fila a eliminar!");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        frmMenu ventana = new frmMenu(productos);
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        frmEditarProducto ventana = new frmEditarProducto(productos, registroPaso);
        tbListaProductos.clearSelection();
        ventana.addWindowListener(new WindowAdapter()
        {
            @Override
            public void windowClosed(WindowEvent e) {
                labelImageCargando.setVisible(true);
                    //To change body of generated methods, choose Tools | Templates.
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            try {
                                llenar();
                            } catch (Exception ex) {
                                System.err.println("Error: " + ex.getMessage());
                            }
                        }
                    });
            }
            
        });
        ventana.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCargando;
    private javax.swing.JLabel labelImageCargando;
    private javax.swing.JTable tbListaProductos;
    // End of variables declaration//GEN-END:variables
}
